<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Mayuresh" failures="1" tests="5" name="demo.session.framework.SeleniumFrameworkTutorials.ProductCatalogueHashMap" time="20.868" errors="0" timestamp="2025-01-06T23:35:23 IST" skipped="1">
  <testcase classname="demo.session.framework.SeleniumFrameworkTutorials.ProductCatalogueHashMap" name="validateOrderFailureDemo" time="2.370">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at demo.session.framework.SeleniumFrameworkTutorials.ProductCatalogueHashMap.validateOrderFailureDemo(ProductCatalogueHashMap.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
    </failure>
  </testcase> <!-- validateOrderFailureDemo -->
  <system-out/>
  <testcase classname="demo.session.framework.SeleniumFrameworkTutorials.ProductCatalogueHashMap" name="validateOrderSummary" time="2.708"/>
  <system-out/>
  <testcase classname="demo.session.framework.SeleniumFrameworkTutorials.ProductCatalogueHashMap" name="validateOrderSubmission" time="6.994"/>
  <system-out/>
  <testcase classname="demo.session.framework.SeleniumFrameworkTutorials.ProductCatalogueHashMap" name="validateOrderFailureDemo" time="4.707">
    <skipped/>
  </testcase> <!-- validateOrderFailureDemo -->
  <system-out/>
  <testcase classname="demo.session.framework.SeleniumFrameworkTutorials.ProductCatalogueHashMap" name="validateOrderSubmission" time="4.089"/>
  <system-out/>
</testsuite> <!-- demo.session.framework.SeleniumFrameworkTutorials.ProductCatalogueHashMap -->
